### ISSUE TITLE
Grafana v6.7.1.

### ISSUE THREAD

**Issue by MatthewMunro** [ayoungprogrammer/grafana-finance#5]
Hi Michael

I am trying install your plugin and wondered if it is compatible with the latest version of Grafana v6.7.1?

I have followed your install instructions:

`grafana-cli plugins install ayoungprogrammer-finance-datasource`

But the plugin is not shown in the `Add data source` list.

I have also tried the `Dev setup` part but notice that the version of Node v6.10.0 required in package.json is deprecated.  I installed a newer version of Node v10.19.0 and changed the package.json but still not able to see the plugin in the data source list.

I hope that you can help?

Thanks

**Comment by ayoungprogrammer** [comment]
Hi Matthew, Sorry if you're having difficulties. I have not been following grafana since I uploaded my plugin. I am currently running my grafana on version 4.2.0. The data source is called "Finance" which you may have missed.

**Comment by juvenn** [comment]
Hey Matthew, just FYI. I have been running this plugin very well on grafana:6.1.4, based on grafana's official docker image. It shall work on 6.7? (Or maybe)

**Comment by MatthewMunro** [comment]
Thanks @ayoungprogrammer and @juvenn for responding.

It turns out that I did not follow the instructions post installing the plugin via Grafana's CLI.

After restarting the Grafana service I am now able to see the Finance plugin and use it as a Data Source.

Thanks @ayoungprogrammer for a great plugin and it is compatible with Grafana v6.7.1.

```
bash-5.0# grafana-cli plugins install ayoungprogrammer-finance-datasource
installing ayoungprogrammer-finance-datasource @ 1.0.0
from: https://grafana.com/api/plugins/ayoungprogrammer-finance-datasource/versions/1.0.0/download
into: /var/lib/grafana/plugins


✔ Installed ayoungprogrammer-finance-datasource successfully 

Restart grafana after installing plugins . <service grafana-server restart>
```

**Comment by MatthewMunro** [comment]
The plugin is compatible with Grafana v.6.7.1.  The Grafana server just needed restarting post install of the plugin using Grafana's CLI.
